name = "PSDTools"
uuid = "ff932bff-df40-4707-8f04-9c99639f1665"
authors = ["KronosTheLate <densbal@live.no> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
